environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: 'cmd /E:ON /V:ON /C .\tools\appveyor\run_with_env.cmd'
    PROJECT_NAME: pyiron

  matrix:
    - PYTHON_VERSION: 3.7
      CONDA: C:\Miniconda37

version: '{build}'
image: Visual Studio 2019

# For testing only...
#skip_non_tags: true

platform:
- x64

init:
  - ps: if ($Env:PLATFORM -eq "x64") { $Env:CONDA = "${Env:CONDA}-x64" }
  - ps: Write-Host $Env:PYTHON_VERSION
  - ps: Write-Host $Env:CONDA
  - ps: Write-Host $Env:PLATFORM
  - ps: Write-Host $Env:APPVEYOR_REPO_TAG
  - ps: Write-Host $Env:APPVEYOR_REPO_TAG_NAME
  - ps: Write-Host $Env:APPVEYOR_REPO_NAME

install:
# Make sure the compiler is accessible
- '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'

# Load the conda root environment, configure and install some packages
- '"%CONDA%\Scripts\activate.bat"'
- "conda config --set always_yes yes --set changeps1 no"
- "conda install -c anaconda setuptools"
- "conda update -q conda"
- "conda create -q --yes -f environment.yml python=%PYTHON_VERSION%"
- "activate pyiron"
- "conda info -a"
- "pip install --pre ."

build: false

test_script:
  # Build the package
  - "python .ci_support/pyironconfig.py"
  - "cat C:/Users/appveyor/.pyiron"
  - "python -m unittest discover tests"
