variables:
  linux: 'ubuntu-16.04'
  mac: 'macos-10.13'
  windows: 'vs2017-win2016'

pr:
  branches:
    include:
      - '*'

jobs:
- job: 'Linux'
  pool:
    vmImage: $(linux)
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH
  - template: .ci_support/azure-unix-test-template.yml

- job: 'OSX'
  pool:
    vmImage: $(mac)
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation
  - template: .ci_support/azure-unix-test-template.yml

- job: 'Windows'
  pool:
    vmImage: $(windows)
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - template: .ci_support/azure-win-test-template.yml