channels:
  - conda-forge
dependencies:
  - ase >=3.20
  - coveralls
  - coverage
  - codacy-coverage
  - defusedxml >=0.6.0
  - future >=0.18.2
  - h5py >=2.10.0
  - matplotlib >=3.2.0
  - mendeleev >=0.5.2
  - molmod >=1.4.5
  - numpy >=1.18.1
  - pandas >=1.0.1
  - phonopy >=2.4.2
  - pymatgen >=2020.9.14
  - pyiron_base >=0.1.30
  - pyscal >=2.10.4
  - pytables >=3.6.1
  - quickff >=2.2.4
  - scipy >=1.4.1
  - seekpath >=1.9.4
  - six >=1.14.0
  - scikit-learn >=0.22
  - spglib >=1.14.1
  - tamkin >=1.2.6
  - yaff >=1.4.2
