channels:
  - conda-forge
dependencies:
  - ase >=3.20.1
  - coveralls
  - coverage
  - codacy-coverage
  - defusedxml >=0.6.0
  - future >=0.18.2
  - h5py >=3.1.0
  - matplotlib >=3.3.3
  - mendeleev >=0.6.1
  - molmod >=1.4.8
  - numpy >=1.19.4
  - pandas >=1.2.0
  - phonopy >=2.8.1
  - pymatgen >=2020.12.31
  - pyiron_base >=0.1.41
  - pyscal >=2.10.6
  - pytables >=3.6.1
  - quickff >=2.2.4
  - scipy >=1.6.0
  - seekpath >=1.9.5
  - six >=1.15.0
  - scikit-learn >=0.24.0
  - spglib >=1.16.0
  - tamkin >=1.2.6
  - yaff >=1.4.2
