channels:
- conda-forge
dependencies:
- gpaw >=20
- jupyter
- lammps =*=*_mpi_*
- nglview
- ipywidgets
- papermill
- seaborn
- sphinxdft >=2.7.0
- sphinxdft-data
- iprpy-data
- pyiron-data >=0.0.29
- pymatgen
- sqsgenerator
