channels:
- conda-forge
dependencies:
- python
- pyiron_atomistic
- pyiron_base
- lammps
- iprpy-data
- gpaw
- sphinxdft >=2.7.0
- sphinxdft-data
- nglview
- seaborn
- pyscal
- jupyterlab
- pyiron_atomistic-data >=0.0.5
- sqsgenerator
- pymatgen
